### ISSUE TITLE
{error,on_load_failure} OTP 17.5 (Ubuntu 14.04)

### ISSUE THREAD

**Issue by adaptunit** [davisp/jiffy#100]
Hi
When I do:
(host@localhost)3> l(jiffy).

I see in my lager "error.log" 
2015-08-01 16:27:03.229 [error] <0.710.0> The on_load function for module jiffy returned {error,{bad_lib,"Library version (2.8) not compatible (with 2.7)."}

Please, can you tell me what kind of "Library" in message?

**Comment by davisp** [comment]
Looks like you built Jiffy with the 18.0 VM and are trying to load it on 17.5.

**Comment by adaptunit** [comment]
I am sorry for it, seems that you're right!

**Comment by anujpradhaan** [comment]
I am facing the a similar issues. 

{error_logger,{{2016,5,12},{10,23,54}},"Unable to load asn1 nif library. Failed with error:~n\"~p, ~s\"~n",[bad_lib,"Library version (2.10) not compatible (with 2.9)."]}

I built it using 18.2 and also trying to load into the same.

**Comment by davisp** [comment]
@anujpradhaan Looks like you've got different Erlang VMs. Though that's the asn1 NIF, you'd have better luck asking on the erlang-questions mailing list.
