### ISSUE TITLE
Records to json

### ISSUE THREAD

**Issue by nOmi7** [davisp/jiffy#101]
I have java client so i need to serlize erlang data mostly records to json n vice versa

I am not able to do that in using jiffy

Any pointers how can i encode records to json ?

**Comment by lpgauth** [comment]
https://gist.github.com/lpgauth/78f81fabbea0f959759d

**Comment by nOmi7** [comment]
@lpgauth  thanks  for the pointer . however I am kinda new to erlang and was looking at ythe jist I did not understand 
```
zip([], []) -> [];
zip([_ | T], [undefined | T2]) -> zip(T, T2);
zip([cars | T], [Cars | T2]) ->
    [{cars, [car_json(Car) || Car <- Cars]} | zip(T, T2)];
zip([H | T], [H2 | T2]) ->
    [{atom_to_binary(H, utf8), H2} | zip(T, T2)].
```

can you please help me understand it also i have 2 recurrsive records 

-record(customer, {id = -1 :: integer(),
  first_name = <<"">> :: binary(),
  last_name = <<"">> :: binary(),
  username = <<"">> :: binary(),
  phone = <<"">> :: binary(),
  photo = #photo{} ,
  headline = #headline{} :: tl_userHeadlineEmpty() | tl_userHeadlineUpdate(),
  bot_info_version = <<"">> :: binary()}).

intern photo has more reccruing records

-record(photo,{photo_id = -1 :: integer(),
  photo_big=  #filelocation{} ,
  photo_small= #filelocation{} }).

-record(filelocation,{dc_id= 5 :: integer(),
  volume_id= -1 :: integer(),
  local_id= -1 :: integer(),
  secret= -1 :: integer(),
  ext= <<"">> :: binary()}).

so i think i need to write more zip funcs 
if you can help me understand it will be great.

**Comment by davisp** [comment]
Not an issue with Jiffy so closing this out.
