### ISSUE TITLE
Options is a list, not clear from docs

### ISSUE THREAD

**Issue by millenaarg** [davisp/jiffy#107]
I have been pulling my hair out as to why the return_maps option gave me errors while being on the latest erlang version. I am new to erlang and I guess it is very clear for more experienced users from looking at the source but maybe it's an idea to specify in the readme.md that a list is expected for decode/2 ? Cheers!

**Comment by lpgauth** [comment]
@millenaarg this is why type specs exists https://github.com/davisp/jiffy/blob/master/src/jiffy.erl#L53

**Comment by millenaarg** [comment]
@lpgauth gotcha. thanks.
