### ISSUE TITLE
use_nil missing for encode

### ISSUE THREAD

**Issue by eproxus** [davisp/jiffy#108]
Decoding with the option `use_nil` is great for using Jiffy from Elixir, however when encoding `nil` gets translated to `"nil"` instead of `null`. It would be great if encode supported the `use_nil` or `{null_term, Term}` option as well.

**Comment by davisp** [comment]
That sounds reasonable.

**Comment by scohen** [comment]
@eproxus This seems to work for me:

```elixir
"null" 
|> :jiffy.decode([:use_nil]) 
|> IO.inspect
|> :jiffy.encode([:use_nil])

nil
"null"
```

**Comment by eproxus** [comment]
Ah, then it only needs documenting under the section `jiffy:encode/1,2` in README.md.

**Comment by davisp** [comment]
Whoops, my bad. I added this to the README.

**Comment by eproxus** [comment]
Is the `null_term` option also supported?

**Comment by davisp** [comment]
It isn't. Whoever updated the decoder didn't bother writing the patch for the encoder. It wouldn't be very difficult to add its just never been on my priority list. The decoder patch cd1b2632083c3724b246c8e8107845d9903bc578 already provides most of the ground work if anyone wants to do the similar changes for encoding.
