### ISSUE TITLE
Rebar3 support?

### ISSUE THREAD

**Issue by testark** [davisp/jiffy#117]
Looks like a stable `rebar3` is out for some time now. Would you consider adding support for `rebar3`?

**Comment by davisp** [comment]
Can you give this branch a whirl?

https://github.com/davisp/jiffy/pull/118

**Comment by philipmw** [comment]
That branch worked for me. Thanks for making it.

homebrew/versions/rebar3: stable 3.1.1 (bottled), HEAD

**Comment by davisp** [comment]
Final version is now on master.
