### ISSUE TITLE
decode error

### ISSUE THREAD

**Issue by qingchuwudi** [davisp/jiffy#125]
There are some zero bytes at the end of the binary,because of AES. And `jiffy:decode` can not filter those zero bytes, while `rfc4627:decode/1` make it. 

Example:
```Erlang
1> Data = <<123,34,100,101,117,105,34,58,34,48,53,56,55,51,52,53,97,51,56,51,49,51,56,51,56,34,44,34,97,99,99,112,101,116,34,58,116,114,117,101,125,0,0,0,0,0,0>>.
2> jiffy:decode(A).
** exception throw: {error,{42,invalid_trailing_data}}
     in function  jiffy:decode/2 (src/jiffy.erl, line 68)
3> rfc4627:decode(A).
{ok,{obj,[{"deui",<<"0587345a38313838">>},{"accpet",true}]},
    []}
```
It is interrupted when dealing with the forty second byte.  

What should I do to make it works for `jiffy:decode` instead of piggybacking length in the frame.

**Comment by davisp** [comment]
Did you try the return_trailer option?

**Comment by davisp** [comment]
Eshell V6.4.1.5  (abort with ^G)
    1> Data = <<123,34,100,101,117,105,34,58,34,48,53,56,55,51,52,53,97,51,56,51,49,51,56,51,56,34,44,34,97,99,99,112,101,116,34,58,116,114,117,101,125,0,0,0,0,0,0>>.
    <<"{\"deui\":\"0587345a38313838\",\"accpet\":true}"...>>
    2> jiffy:decode(Data, [return_trailer]).
    {has_trailer,{[{<<"deui">>,<<"0587345a38313838">>},
               {<<"accpet">>,true}]},
             <<0,0,0,0,0,0>>}
    3> Data2 = <<123,34,100,101,117,105,34,58,34,48,53,56,55,51,52,53,97,51,56,51,49,51,56,51,56,34,44,34,97,99,99,112,101,116,34,58,116,114,117,101,125>>.
    <<"{\"deui\":\"0587345a38313838\",\"accpet\":true}">>
    4> jiffy:decode(Data2, [return_trailer]).
    {[{<<"deui">>,<<"0587345a38313838">>},{<<"accpet">>,true}]}

Although if you use return_trailer you'll have to wrap the jiffy call so that it can throw away any trailing zeroes if they exist.

**Comment by qingchuwudi** [comment]
Yes, I did. 
When zeroes are part of invaild data, both work well. And if zeroes are the part of valid data, new issues come out:

```Erlang
3> jiffy:decode(<<123,34,100,101,117,105,34,58,34,48,53,56,55,51,52,53,97,51,56,51,49,51,56,51,56,34,44,34,97,99,99,112,101,116,34,58,116,114,117,101,125,0,0,0,101,125>>, [return_trailer,return_maps]).
{has_trailer,#{<<"accpet">> => true,
               <<"deui">> => <<"0587345a38313838">>},
             <<0,0,0,101,125>>}
4> 6> rfc4627:decode(<<123,34,100,101,117,105,34,58,34,48,53,56,55,51,52,53,97,51,56,51,49,51,56,51,56,34,44,34,97,0,99,112,101,116,34,58,116,114,117,101,125,0,0,0,0,101,125>>).
{ok,{obj,[{"deui",<<"0587345a38313838">>},
          {[97,0,99,112,101,116],true}]},
    "e}"}
5> jiffy:decode(<<123,34,100,101,117,105,34,58,34,48,53,56,55,51,52,53,97,51,56,51,49,51,56,51,56,34,44,34,97,0,99,112,101,116,34,58,116,114,117,101,125,0,0,0,0,0,0>>, [return_trailer,return_maps]).   
** exception throw: {error,{30,invalid_string}}
     in function  jiffy:decode/2 (src/jiffy.erl, line 68)
6> rfc4627:decode(<<123,34,100,101,117,105,34,58,34,48,53,56,55,51,52,53,97,51,56,51,49,51,56,51,56,34,44,34,97,0,99,112,101,116,34,58,116,114,117,101,125,0,0,0,0,0,0>>).
{ok,{obj,[{"deui",<<"0587345a38313838">>},
          {[97,0,99,112,101,116],true}]},
    []}

```

**Comment by davisp** [comment]
Well, zeroes in the middle of your data means that its not actually valid data. For this particular case the zero happens in the middle of a string wihch rfc4627 apparently happily decodes. Jiffy on the other hand requires that the input string is valid UTF-8 and rejects anything that isn't. There is an option `force_utf8` that will replace bad data with the unicode replacement character though that doesn't sound like what you're after. I'd look into whatever you have generating your JSON strings and see if you can fix whatever is placing those zeroes in your data.
