### ISSUE TITLE
Cannot decode this string, what's wrong ?

### ISSUE THREAD

**Issue by andreabenini** [davisp/jiffy#131]
Here's a simple and valid JSON string:
> {"FN":"name","N":{"FAMILY":"Surname","GIVEN":"what"},"PHOTO":{"BINVAL":"/9j/4AA1khd930vZ2PZ\r\n","TYPE":"image/jpeg"}}

Then with Erlang:
`Body = <<"{\"FN\":\"name\",\"N\":{\"FAMILY\":\"Surname\",\"GIVEN\":\"what\"},\"PHOTO\":{\"BINVAL\":\"/9j/4AA1khd930vZ2PZ\r\n\",\"TYPE\":\"image/jpeg\"}}">>.`
> <<"{\"FN\":\"name\",\"N\":{\"FAMILY\":\"Surname\",\"GIVEN\":\"what\"},\"PHOTO\":{\"BINVAL\":\"/9j/4AA1khd930vZ2PZ\r\n\",\"TYPE\":\"image/jpeg\"}}">>

`jiffy:decode(Body).`
> ** exception throw: {error,{92,invalid_string}}
>     in function  jiffy:decode/2 (src/jiffy.erl, line 68)

Please note that the above string is legal.
And when I use this:

`Body = <<"{\"FN\":\"name\",\"N\":{\"FAMILY\":\"Surname\",\"GIVEN\":\"what\"},\"PHOTO\":{\"BINVAL\":\"9j4AA1khd930vZ2PZ\",\"TYPE\":\"image/jpeg\"}}">>.`
> <<"{\"FN\":\"name\",\"N\":{\"FAMILY\":\"Surname\",\"GIVEN\":\"what\"},\"PHOTO\":{\"BINVAL\":\"9j4AA1khd930vZ2PZ\",\"TYPE\":\"image/jpeg\"}}">>

`jiffy:decode(Body).`
>{[{<<"FN">>,<<"name">>},
>  {<<"N">>,
>   {[{<<"FAMILY">>,<<"Surname">>},{<<"GIVEN">>,<<"what">>}]}},
>  {<<"PHOTO">>,
>   {[{<<"BINVAL">>,<<"9j4AA1khd930vZ2PZ">>},
>     {<<"TYPE">>,<<"image/jpeg">>}]}}]}

But this works. why ?

**Comment by andreabenini** [comment]
Nevermind... I guess I have found something stupid from console (wrong chars or whatever). Same code inside a function works so it's not a fault.

Thanks

**Comment by davisp** [comment]
You weren't escaping your \r\n when you created the Erlang binary.

```erlang
Body = <<"{\"FN\":\"name\",\"N\":{\"FAMILY\":\"Surname\",\"GIVEN\":\"what\"},\"PHOTO\":{\"BINVAL\":\"/9j/4AA1khd930vZ2PZ\\r\\n\",\"TYPE\":\"image/jpeg\"}}">>.
```

Notice, the extra `\` character for `\r` and `\n`. Without it you were actually inserting a raw line feed and carriage return byte into the binary which does make it invalid JSON.

**Comment by andreabenini** [comment]
Seen it... but too late ! thanks again
