### ISSUE TITLE
crash in encode_init(), enif_priv_data()

### ISSUE THREAD

**Issue by zwizwa** [davisp/jiffy#132]
Regarding a7db72493d2288533afbb417d5c2e6f11db84639, but it has been doing this for a while.
This is Erlang from Debian amd64 1:18.3.4.4+dfsg-1

Crash below is triggered by reloading an arbitrary module:
- fresh start of beam + application
- jiffy:encode([])
- editing a arbitrary module foo.erl + recompile the beam file
- l(foo)
- jiffy:encode([])

The recompile step is essential to reproduce. l(foo) without recompile has no effect.

Thread 15 "1_scheduler" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fc1357bf700 (LWP 7851)]
0x0000000000003ff6 in ?? ()
(gdb) bt
#0  0x0000000000003ff6 in ?? ()
#1  0x00007fc131dedd69 in encode_init (env=0x7fc1357bee30, argc=2, argv=0x7fc137c400c0) at c_src/encoder.c:577
#2  0x00000000004378c7 in process_main ()
#3  0x00000000004b369c in ?? ()
#4  0x00000000005b8127 in ?? ()
#5  0x00007fc13893a464 in start_thread (arg=0x7fc1357bf700) at pthread_create.c:333
#6  0x00007fc13847597f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

(gdb) frame 1
#1  0x00007fc131dedd69 in encode_init (env=0x7fc1357bee30, argc=2, argv=0x7fc137c400c0) at c_src/encoder.c:577

577         jiffy_st\* st = (jiffy_st*) enif_priv_data(env);

**Comment by davisp** [comment]
Interesting. Can you be a bit more specific on your reproduction though? For instance, this doesn't work:

```erlang
1> l(foo).
{module,foo}
2> jiffy:encode([]).
<<"[]">>
3> % Edit foo.erl
3> l(foo).
{module,foo}
4> jiffy:encode([]).
<<"[]">>
```

Could you be more specific on what you include in "+ application"? For instance, are you using any other NIFs? Given the number of people that use Jiffy and this being the first report I'd wager its something else corrupting RAM in the VM which is then passed to Jiffy. Granted its not impossible Jiffy has a latent bug. :D

**Comment by zwizwa** [comment]
"+ application" is big, though I believe jiffy is the only NIF library loaded outside of the main Erlang distribution. I'll see if i can trigger the bug using a simpler set.

**Comment by zwizwa** [comment]
This is not an issue with jiffy. I was copying the new .so over the old .so that was still linked into the VM hence corrupting the code that still needed to run before the VM unloaded it. "cp --remove-destination" fixed it. It finally hit me after making a very simple NIF library and running into the same problem.

**Comment by davisp** [comment]
Ahh. Thanks for the follow up!
