### ISSUE TITLE
Cannot compile 0.14.10

### ISSUE THREAD

**Issue by myronmarston** [davisp/jiffy#133]
With #121 merged and released as 0.14.10 I updated jiffy in my Elixir app and promptly ran into a compile error:

```
$ mix deps.compile jiffy
===> Compiling jiffy
sh: /Users/myron/moz/delorean/deps/jiffy/enc: No such file or directory
sh: line 0: exec: /Users/myron/moz/delorean/deps/jiffy/enc: cannot execute: No such file or directory
===> Hook for compile failed!

** (Mix) Could not compile dependency :jiffy, "/Users/myron/.mix/rebar3 bare compile --paths "/Users/myron/moz/delorean/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile jiffy", update it with "mix deps.update jiffy" or clean it with "mix deps.clean jiffy"
```

Any idea?

**Comment by davisp** [comment]
Ah, I bet I don't have hex configured properly to include that. I only eyeballed the file list and probably missed it.

**Comment by davisp** [comment]
@myronmarston My bad for not looking at that file list closer. Apparently the hex plugin has some sort of file list internally so I have to configure it with an explicit list of files and directories. Give 0.14.11 a whirl and see if it fixes things for you.

**Comment by myronmarston** [comment]
0.14.11 works fine . Thanks for the prompt fix!

**Comment by davisp** [comment]
No problem. Thanks for the follow up!
