### ISSUE TITLE
Debug jiffy module

### ISSUE THREAD

**Issue by msdeep14** [davisp/jiffy#135]
I'm doing some modifications in the jiffy module, to understand the flow of functions, I want to use printf statements, I used the c printf function, but it don't display any output on terminal, what is way the do this?

**Comment by lpgauth** [comment]
Try adding `\r\n` to you debug statements.

**Comment by msdeep14** [comment]
I tried - printf("inside jiffy \n"); in decoder.c
and then on terminal I did jiffy:decode(<<"{\"foo\":\"bar\"}">>). 
It didn't worked.

**Comment by davisp** [comment]
Erlang does some funny things to its console streams. If memory serves you can do this:

```c
fprintf(stderr, "inside jiffy\r\n");
```

**Comment by msdeep14** [comment]
`frintf` also didn't worked.

Here is the code snippet:

`void
  dec_init(Decoder* d, ErlNifEnv* env, ERL_NIF_TERM arg, ErlNifBinary* bin)
  {
    d->env = env;
    d->arg = arg;
    fprintf(stderr, "mandeep singh :: inside jiffy dec init \r\n");
   // printf("mandeep :: hello-> inside dec_init c \n");
    d->p = (char*) bin->data;
    d->u = bin->data;
    d->len = bin->size;

    // I'd like to be more forceful on this check so that when
    // we run a second iteration of the decoder we are sure
    // that we're using the same binary. Unfortunately, I don't
    // think there's a value to base this assertion on.
    if(d->i < 0) {
        d->i = 0;
    } else {
        assert(d->i <= d->len && "mismatched binary lengths");
    }
}`
