### ISSUE TITLE
Non English decode not working

### ISSUE THREAD

**Issue by nOmi7** [davisp/jiffy#136]
```
jiffy:decode(<<"{\"ok \": \"Nederland Българс\"}">>).  
** exception throw: {error,{20,invalid_string}}
     in function  jiffy:decode/2 (src/jiffy.erl, line 68)
```

**Comment by nOmi7** [comment]
@davisp can you please enlighten me on this ... is it known issue or some bug?

**Comment by davisp** [comment]
I'm pretty sure this is probably that there's a break in the unicode. Are you pasting that into a shell? If memory serves the shell doesn't do unicode correctly but if you put it in a compiled file it'll work. If you can send me the raw bytes I can double check that the UTF-8 decoder/encoder isn't missing an edge case.

**Comment by davisp** [comment]
Pasting that binary into the shell gives me this set of bytes:

```erlang
<<123,34,111,107,32,34,58,32,34,78,101,100,101,114,108,97,110,100,32,17,74,59,51,48,64,65,34,125>>
```

That byte value of 17 is where Jiffy rejects it which it should as that's a control byte value and not part of a UTF-8 sequence.

**Comment by davisp** [comment]
However, pasting it into a file and doing a hex dump of the file gives this byte sequence starting where that 17 is:

0xD091D1

Which is also invalid UTF-8 cause the second D breaks the continuation byte sequence expected for the leading D.

**Comment by nOmi7** [comment]
ok i do see the 17 thingy on raw bytes
unicode:characters_to_binary(<<"Българс">>,unicode,utf8).                   
<<17,74,59,51,48,64,65>>
I did not understand the pasting to file and doing hexdump ..
What should be the next step to resolve it .. ? I am trying to run the program without shell by then ..


"if memory serves the shell doesn't do unicode correctly" why is that ? is there any way to increase some memory to get this running ?

<<17,74,59,51,48,64,65>> are the raw bytes for the decoder testing for you.

**Comment by davisp** [comment]
Whatever that unicode function is doing, its not anything related to encoding those characters as UTF-8. Those bytes encode:

```^QJ;30@A```

(Where ^Q is DC1 - device control 1)

The issue here is that what ever you're giving to Jiffy is not UTF-8 encoded. If you ensure that you're passing UTF-8 binaries then Jiffy will work just fine. Here's an example

```
$ cat foo.txt 
{"unicode_data": "∂˚∆∂ƒüîøµñéå∑¢•™£¢º£"}
$ erl -pa ebin/
Erlang/OTP 17 [erts-6.4.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [kernel-poll:false]

Eshell V6.4.1.5  (abort with ^G)
1> {ok, Json} = file:read_file("foo.txt").
{ok,<<123,34,117,110,105,99,111,100,101,95,100,97,116,97,
      34,58,32,34,226,136,130,203,154,226,136,134,226,...>>}
2> {[{<<"unicode_data">>, String}]} = jiffy:decode(Json).
{[{<<"unicode_data">>,
   <<226,136,130,203,154,226,136,134,226,136,130,198,146,
     195,188,195,174,195,184,194,181,195,177,195,169,...>>}]}
3> file:write_file("bar.txt", String).
ok
4> 
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
$ cat bar.txt 
∂˚∆∂ƒüîøµñéå∑¢•™£¢º£
```

**Comment by davisp** [comment]
Also, I'll note that I'm reading and writing files there because the Erlang shell does not properly handle unicode as I mentioned before.

**Comment by nOmi7** [comment]
Ok i got some trick here 
if i run from the shell with /utf8 all work as it should ..  I am good for now Thanks for your help and attention @davisp  Ill test this more in project and report incase of any issues.
