### ISSUE TITLE
incorrect list intermittently

### ISSUE THREAD

**Issue by grizzly-monkey** [davisp/jiffy#137]
For our project requirement what we did is made key to return as list instead of binary.
original
jiffy:decode(<<"{\"client_id\":35}">>).         
{[{<<**"client_id"**>>,35}]}

we modified the decoder.c to return key as list
jiffy:decode(<<"{\"first_name\":\"Killer\"}">>).
[{**"client_id"**,35}]

for this what we changed in decoder.c is 

```
parse:
    if(!has_escape) {
        *value = enif_make_sub_binary(d->env, d->arg, st, (d->i - st - 1));
        char* key_string = 0;
        key_string = (char*)malloc(sizeof(char)*10000);  **/// CAN THIS BE ISSUE ?**
        strncpy(key_string, d->p+st, (d->i - st-1));
	if(is_key == true){
            *value = enif_make_string(d->env,key_string,ERL_NIF_LATIN1);
	}else{
	    *value = enif_make_sub_binary(d->env, d->arg, st, (d->i - st - 1));
	}
        return 1;
    }
```

after this change we are intermittently decoding as 
jiffy:decode(<<"{\"client_id\":35}">>).     
{[99,108,105,101,110,116,95,105,100,7],35}

would be able to help please ?

**Comment by davisp** [comment]
You've got a trailing byte in your list there. If memory serves malloc
doesn't zero out memory so your make_string call is just grabbing data
until the first null.

Although I'm not seeing why you're allocating a buffer here anyway. Theres
no need to copy out of the json binary storage just to pass it back into
Erlang.

The call you want to use is enif_make_string_len which will take similar
arguments as your strncpy call.

Also you have an extra make_sub_binary call there as well.

**Comment by nOmi7** [comment]
yea i just saw extra  call ... 
I am not good at all with C so had bad code there 
can this be good ?

```
parse:
    if(!has_escape) {
	if(is_key == true){
            *value = enif_make_string_len(d->env, d->p+st, (d->i - st-1),ERL_NIF_LATIN1);
              or
            *value = enif_make_string_len(d->env, (char*)d->p+st, (d->i - st-1),ERL_NIF_LATIN1);
	}else{
	    *value = enif_make_sub_binary(d->env, d->arg, st, (d->i - st - 1));
	}
        return 1;
    }
```
Please help me correct it ill be very thankful.

**Comment by davisp** [comment]
Looks right to me. Though if you're not comfortable with C it'd probably be
a lot easier to just transform the returned JSON. I'd be a bit surprised to
see a huge performance difference.

**Comment by aknrdureegaesr** [comment]
@nOmi7 : It's been a year... Can this be closed?
