### ISSUE TITLE
Can't compile with erlang 19.3

### ISSUE THREAD

**Issue by t0il3ts0ap** [davisp/jiffy#141]
Erlang shell
```
➜  jiffy git:(master) ✗ erl
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.3  (abort with ^G)
1>
User switch command
 --> q
```

With rebar
```
➜  jiffy git:(master) ✗ ./rebar compile
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{crypto,start,[],[]},
                                 {rebar,run_aux,2,[]},
                                 {rebar,main,1,[]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,760}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]},
                                 {init,start_em,1,[]},
                                 {init,do_boot,3,[]}]}}
```

With rebar3 
```
➜  jiffy git:(master) ✗ rebar3 compile
===> Rebar dependency crypto could not be loaded for reason {"no such file or directory",
                                                                    "crypto.app"}
```

**Comment by t0il3ts0ap** [comment]
Ohh further investigation shows its a kerl issue
https://github.com/evax/kerl/issues/13

Closing this!

**Comment by oladipo** [comment]
have the same problem.. didn't use kerl at all... wonder why

**Comment by davisp** [comment]
@oladipo The underlying issue is when Erlang builds without crypto support. Try running `crypto:start()` in your erl shell.

**Comment by sachithnalaka** [comment]
@davisp When I try to execute `crypto:start().` I got **** exception error: undefined function crypto:start/0
**

**Comment by davisp** [comment]
@sachithnalaka You need to rebuild Erlang with crypto/openssl support then.

**Comment by davisp** [comment]
Which I should mention likely means you either need to do something like "sudo apt-get install libssl-dev" or "brew install openssl" depending on your platform and then re-run ./configure (or re-build via kerl).

**Comment by XxKavosxX** [comment]
This works for me!
I intalled these packages and ./configure -> make -> make_testes ->make install
[http://blog.differentpla.net/blog/2019/01/30/erlang-build-prerequisites/]
)
