### ISSUE TITLE
Rebar cannot compile dependencies on Windows: deps/jiffy/c_src/decoder.c(4): fatal error C1083: Cannot open include file: 'assert.h': No such file or directory

### ISSUE THREAD

**Issue by stefek99** [davisp/jiffy#144]
Hi,

I know nothing _(very little)_ about Erlang, Rebar, Jiffy and solving dependencies on Windows. All I'm trying to do is to support an [open-source project](https://github.com/aeternity/testnet/issues/5#issuecomment-295984391) and by providing instructions how to run on Windows - wider adoption, more available, etc...

On **Mac** and **Ubuntu** it works just fine: 
```
Michals-MacBook-Pro:testnet zen$ rebar get
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
Michals-MacBook-Pro:testnet zen$ rebar compile
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
```

On Windows:
```
c:\Stefan\testnet>rebar get
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)

c:\Stefan\testnet>rebar compile
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
Compiling c:/Stefan/testnet/deps/jiffy/c_src/decoder.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23918 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

decoder.c
c:/Stefan/testnet/deps/jiffy/c_src/decoder.c(4): fatal error C1083: Cannot open include file: 'assert.h': No such file or directory
ERROR: compile failed while processing c:/Stefan/testnet/deps/jiffy: rebar_abort
```

## Windows

![image](https://cloud.githubusercontent.com/assets/249703/25271015/83b71bca-267a-11e7-98d4-ad35f0e02505.png)

## Mac

![image](https://cloud.githubusercontent.com/assets/249703/25271031/9813bee8-267a-11e7-806d-f53226107f9d.png)

Note that `assert.h` isn't present in neither of platforms...

If this is a question for Rebar / StackOverflow - let me know...

_(as I said I know relatively little about managing dependencies in Erlang)_

---

**EDIT:** seems related to #59

**Comment by wohali** [comment]
There is a bug in enc which should be patched by https://github.com/davisp/erlang-native-compiler/pull/1 . 

However, `assert.h` is a system include file. Your build environment may not be set up correctly. 

With the enc patch above I am able to successfully build jiffy under VS2013 x64 Community Edition. I haven't tried VS2015 which seems to be what you're running.

**Comment by stefek99** [comment]
I don't know what I'm using. Following path of least resistance, 

> Too bad I have Visual Studio already installed - won't allow me to install standalone compiler - adding some extra packages - http://stackoverflow.com/questions/31953769/visual-studio-doesnt-have-cl-exe

_(managed to see my comment in the related issue)_

I'm not longer involved in the project and I'm reinstalling OS anyway.
