### ISSUE TITLE
seems force_utf8 option not working properly

### ISSUE THREAD

**Issue by ludwikbukowski** [davisp/jiffy#154]
For special characters it always returns the same, strange binary:

```
2> jiffy:encode(<<"£">>, [force_utf8]).
<<34,239,191,189,34>>
3> jiffy:encode(<<"§">>, [force_utf8]).
<<34,239,191,189,34>>
```
works for typical ASCII characters though:

```
4> jiffy:encode(<<"a">>, [force_utf8]).
<<"\"a\"">>
```

IMO this is issue related to `jiffy_utf8:loose_decode/3` function

Is it expected behaviour?

**Comment by ludwikbukowski** [comment]
Ok, so it iw working when you use `utf8` specyfier:
```
28> jiffy:encode(<<"£"/utf8>>, [force_utf8]) == jiffy:encode(<<"§"/utf8>>, [force_utf8]).
false
```

closing the issue

**Comment by davisp** [comment]
Oh, yeah, that one gets me every time its reported! I wonder if there's a non-terrible way to detect that to help people like you doing testing in the shell.

**Comment by ludwikbukowski** [comment]
maybe the specific example in README :P
