### ISSUE TITLE
failed tests in OpenIndiana with huge numbers

### ISSUE THREAD

**Issue by grueni** [davisp/jiffy#157]
I try to compile CouchDB 2.1 with OpenIndiana as 32bit application with Erlang 17.5
CouchDB hast the newest source of jiffy 0.14.1 embedded.
make test produces 3 errors with huge numbers.
There seems to be a 32bit int used where a 64bit int should be used.
Do you have a hint where this conversion is handled in the source of jiffy?

    jiffy_03_number_tests:27: gen (Decode)...*failed*
in function jiffy_03_number_tests:'-gen/2-fun-0-'/2 (test/jiffy_03_number_tests.erl, line 27)
**error:{assertEqual_failed,[{module,jiffy_03_number_tests},
                     {line,27},
                     {expression,"dec ( J1 )"},
                     {expected,1234567890123456789012345},
                     {value,2147483647}]}

    jiffy_03_number_tests:28: gen (Encode)...ok
    [done in 0.020 s]
  1310050760199
    jiffy_03_number_tests:27: gen (Decode)...*failed*
in function jiffy_03_number_tests:'-gen/2-fun-0-'/2 (test/jiffy_03_number_tests.erl, line 27)
**error:{assertEqual_failed,[{module,jiffy_03_number_tests},
                     {line,27},
                     {expression,"dec ( J1 )"}
                     {expected,1310050760199},
                     {value,2147483647}]}

    jiffy_03_number_tests:28: gen (Encode)...[0.001 s] ok
    [done in 0.021 s]
  1234567890123456789012345.0
    jiffy_03_number_tests:27: gen (Decode)...ok
    jiffy_03_number_tests:28: gen (Encode)...ok
    [done in 0.021 s]
  1234567890123456789012345.0E3
    jiffy_03_number_tests:27: gen (Decode)...ok
    jiffy_03_number_tests:28: gen (Encode)...ok
    [done in 0.021 s]
  1234567890123456789012345012
    jiffy_03_number_tests:27: gen (Decode)...*failed*
in function jiffy_03_number_tests:'-gen/2-fun-0-'/2 (test/jiffy_03_number_tests.erl, line 27)
**error:{assertEqual_failed,[{module,jiffy_03_number_tests},
                     {line,27},
                     {expression,"dec ( J1 )"},
                     {expected,1234567890123456789012345012},
                     {value,2147483647}]}

    jiffy_03_number_tests:28: gen (Encode)...ok
    [done in 0.022 s]

**Comment by davisp** [comment]
@grueni Odd. Care to try this diff and see if it fixes things?

https://github.com/davisp/jiffy/compare/fix-large-int-conversions

**Comment by grueni** [comment]
Thanks for the prompt answer.

I did exactly this but used an unsigned long long.
Function strtol returns in Solaris a 4 byte int and in Linux a 8 byte long.
To get the maximum number I used now stroull unsigned long long.
See here:
https://github.com/grueni/oi-userland/commit/123f9bf793a14add0ea7831ffb22ec1dec963506#diff-bf5ba420029a51f53bdb6f40d6dda81c
This seems to be the portable solution.
I undersatnd what is going on and what is testable.

But I did not understand the sense of the test above:
{<<"1234567890123456789012345">>, 1234567890123456789012345},
This test must fail. 
The expected value is the maximum of the type of variable lval and is in my case 18446744073709551615 and in your case 9223372036854775807.
If this test is used 
- the expected value for decoding must be one of the two above and true for the assert check
- or false for the assert check with the expected value of 1234567890123456789012345
Did I understand this correctly?

**Comment by davisp** [comment]
@grueni Using an unsigned long long seems wrong as we need to be able to decode large negative numbers as well. I'll make sure and add a test for that. You mentioned strtol and strtoull, is there no strtoll like I used in the patch?

For the 1234567890123456789012345 test I think you're missing that Erlang supports big integers and Jiffy handles that by detecting an error during conversion and returning a "partially decoded" value back to Erlang which then handles the bignum decoding here:

https://github.com/davisp/jiffy/blob/master/src/jiffy.erl#L107-L120

**Comment by grueni** [comment]
strtoll is fine (forgot to mention) and returns an signed long long.
Thanks for the explanation how this is handled by erlang + jiffy.
With strtoll the assert returns true.
