### ISSUE TITLE
'.' is not recognised as an internal command

### ISSUE THREAD

**Issue by matthewslouismarie** [davisp/jiffy#160]
Hi all,

I am working on an Erlang project. I am trying to add Elvis to it. Elvis requires a few dependencies, and one of them depends on jiffy.
It looks like the latest version of jiffy is broken. On my side, when I try to compile, I get:
```
===> Compiling jiffy
'.' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
===> Hook for compile failed!
```
Which translates to: `'.' is not recognised as an internal or external command, an executable program or a commands file`.

I think version 0.4.12 of jiffy does not have this problem. But I don't know if there is a way for me to force elvis to use this version without modifying elvis (I need to run rebar3 escriptize).

**Comment by davisp** [comment]
Is this on Windows? Assuming so you'll want a version of Jiffy that has this commit:

https://github.com/davisp/jiffy/commit/a13b9e1ec9849a3bc385fdbd42d5de63c6681bf5

Which as you point out is 0.14.12. Updating Elvis is out of my ability though. Not sure if there's a way to convince it to use something newer. Though if memory serves on rebar3 you can override it in your top level project by declaring a direct dependency on Jiffy.

**Comment by matthewslouismarie** [comment]
Thanks for the reply! Yes, it's on Windows.
This is what I did, and the project (including jiffy) compile well this way. The problem is, I still cannot run `rebar3 escriptize` from elvis's directory. But that might not be what I'm supposed to do, so I'll keep on looking.

**Comment by davisp** [comment]
Not sure what you're trying to escriptize, but Jiffy being a NIF won't play well with that as you'll need pure Erlang files for that to work. Sounds like you've fixed the underlying issue though so I'm gonna close this out.
