### ISSUE TITLE
inconsistent handling of duplicate keys with return_maps 

### ISSUE THREAD

**Issue by ldgabbay** [davisp/jiffy#162]
When decoding a JSON object with duplicate keys and with the `return_maps` flag set, the first discovered value is used.  This can be seen with the following:

```
1> jiffy:decode(<<"{\"x\": 1, \"x\": 2}">>, [return_maps]).
#{<<"x">> => 1}
```

[RFC7159](https://tools.ietf.org/html/rfc7159#section-4) suggests using the value of the last match, which is also the intended behavior of the option `dedupe_keys`.

```
2> jiffy:decode(<<"{\"x\": 1, \"x\": 2}">>, [dedupe_keys]).
{[{<<"x">>,2}]}
```

Even with `dedupe_keys` set, the `return_maps` implementation returns the first value.
```
3> jiffy:decode(<<"{\"x\": 1, \"x\": 2}">>, [return_maps, dedupe_keys]).
#{<<"x">> => 1}
4> jiffy:decode(<<"{\"x\": 1, \"x\": 2}">>, [dedupe_keys, return_maps]).
#{<<"x">> => 1}
```

With `return_maps`, with or without `dedupe_keys`, we suggest the result should use the last match, which in this example would be:
```
#{<<"x">> => 2}
```

**Comment by aknrdureegaesr** [comment]
The fix has been merged as of 0.15.0, so I think this issue can be closed.
