### ISSUE TITLE
Error when try decode JSON when in field integer the first number is 0

### ISSUE THREAD

**Issue by vkatsuba** [davisp/jiffy#166]
Hi, I stumbled upon a strange behavior during decoding JSON more information is given below

`1> jiffy:decode(<<"{\"code\": 0123}">>).`
`** exception throw: {error,{11,invalid_json}}
     in function  jiffy:decode/2 /folder_app/lib/jiffy/src/jiffy.erl, line 69)`

`2> jiffy:decode(<<"{\"code\": 123}">>). `
`{[{<<"code">>,123}]}`

Branch tag is **0.14.11** but this error also appears in **0.15.1** too.
Looking forward to updates.

Best regards,
V. Katsuba

**Comment by davisp** [comment]
@vkatsuba That's not an error. `0123` isn't a valid integer encoding as per the JSON grammar.

For comparison, here's Python's behavior:

```
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> json.loads('{"code": 0123}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 1 column 11 (char 10)
```

**Comment by vkatsuba** [comment]
Hi @davisp. Thanks for quick answer. Agreed, unfortunately I found a little later a reply in RFC, pls see information below

https://tools.ietf.org/html/rfc7159:

> 6.  Numbers
  The representation of numbers is similar to that used in most
  programming languages.  A number is represented in base 10 using
  decimal digits.  It contains an integer component that may be
  prefixed with an optional minus sign, which may be followed by a
  fraction part and/or an exponent part.  Leading zeros are not
  allowed.
A fraction part is a decimal point followed by one or more digits.

I was confused simply by the fact that in Erlang will be **true**
`1> erlang:is_integer(01234).`

Many thanks for your time.

Cheers!

**Comment by davisp** [comment]
No worries!
