### ISSUE TITLE
Use inspect_iolist_as_binary for iolists

### ISSUE THREAD

**Issue by seriyps** [davisp/jiffy#169]
I noticed that jiffy uses `iolist_to_binary/1` when decoding json from iolist. But it will create refcounted binary

https://github.com/davisp/jiffy/blob/ee8b48cb448a999e1fddbb5e2e32e7dfe33acf5c/src/jiffy.erl#L80

Maybe it would worth to use [inspect_iolist_as_binary](https://github.com/erlang/otp/edit/maint/erts/doc/src/erl_nif.xml#L1597)? it allocates temporary memory segment and might be more efficient

https://github.com/erlang/otp/blob/759af43a8213f6c0b39a76ae062a89b726cd4c25/erts/emulator/beam/erl_nif.c#L1117-L1139

I haven't done any benchmarks.

**Comment by davisp** [comment]
That conversion is done preemptively because a) it has to be done regardless of whether we use inspect_iolist_as_binary and b) doing it this way means we can keep our state across yielding back to the VM.
