### ISSUE TITLE
Optimization of the jiffy NIFs

### ISSUE THREAD

**Issue by KennethL** [davisp/jiffy#175]
Hi,
The is a pull request on the erlang/otp project https://github.com/erlang/otp/pull/2143 where 2 new BIFs json_to_term and term_to_json is implemented. The reason for implementing json encode/decode as BIFs is performance and the author of the pull request have done a series of measurements showing the performance of different json implementations. The OTP team does not want that functionality and suggest that we instead put an effort in a separate application using NIFs. Jiffy is the popular json application using NIFs and we think that it is possible to optimize Jiffy to become almost as fast as the BIF solution. In the pull request there is a number of suggestions for how to optimize Jiffy. @davisp Are you interested in taking part in the optimization effort? Or positive to taking in this as a pull request?

**Comment by davisp** [comment]
@KennethL I'm always interested in improving Jiffy! I'd definitely accept PRs to improve performance and/or eventually get around to attempting some of those optimizations. Though for anyone that's interested I'd not wait on me to get around to it on my own.

I'd wager that the way Jiffy is maintaining state is likely a lot of the issue. There were a couple interesting ideas about improving that in the PR discussion that are interesting. Specifically only convert to an Erlang representation when yielding and the possibility to switch to a dirty NIF so we only ever yield once are both interesting.

The integer encoding optimization is also interesting and looks like it'd be a drop in replacement in Jiffy.

**Comment by davisp** [comment]
I've merged John's PR today.
