### ISSUE TITLE
Large documents and commit a1196ba7549837283eb526e8725f299811bdfcf3

### ISSUE THREAD

**Issue by peffis** [davisp/jiffy#178]
Hi, 

I'm trying to debug a problem that has come to my attention after re-building a jiffy-based app that has not been built for some time - and therefore a new version of jiffy was included this time. 

When encoding very large maps with jiffy:encode(Map) the result nowadays becomes an io_list and not always a single binary as I think it used to. Is this some API change that I am not aware of? Was it introduced by a1196ba7549837283eb526e8725f299811bdfcf3 for instance? The code used to be able to handle large maps like that and the result was only one big binary and I am trying to understand when this changed and how I should go about fixing my application if it is an intentional change in jiffy.

**Comment by davisp** [comment]
This is intentional. Jiffy has always been defined as returning an iolist due to how bignums are handled. There was a recent change to how strings are handled which causes iolists to be more common.

You can either wrap your jiffy calls in iolist_to_binary or pass it directly to an io function that takes one.

**Comment by peffis** [comment]
I see. Perhaps I have just missed it but would it be possible to more clearly highlight the return type in the docs a bit? The readme does not seem to specify it, or? I, falsely, assumed the return type would always be a binary, which now caused some serious issues when it turned out that there will be a list for larger docs

**Comment by lpgauth** [comment]
It's part of the function specs, see:
https://github.com/davisp/jiffy/blob/master/src/jiffy.erl#L83

**Comment by peffis** [comment]
Yes, that is true. Not all people read through the source code of a dependency though so all I am saying is that perhaps it is a good suggestion to make the return type more clear in the readme. I believe it is a common (not saying it is a good) practice in the Erlang community to just explore API:s by typing examples in the shell and the wrong assumptions could of course be drawn from that. Then in this particular case, where the return type is still an iolist but the behaviour of when this is returned as a single binary or a list has changed, it is perhaps also worth pointing out that this behaviour change was done. But I am not complaining, I am very grateful for the work on jiffy and I have only myself to blame for the wrong conclusions drawn.
