### ISSUE TITLE
stacktrace,[{erlang,byte_size}]

### ISSUE THREAD

**Issue by vigneswaranm** [davisp/jiffy#181]
I am getting below error when i use the latest version of the code it works fine when i use tag, "0.15.2"
 
is there any limit implemented?

stacktrace,[{erlang,byte_size}]

trace,[{erlang,byte_size,[[<<"[\"message\",{\"type\":\"doc\",\"body\":">>,<<"\"%7B%22doc%22%3A%7B%22href%22%3A%22https%3A%2F%2Fcdpn.io%2Fboomboom%2Fv2%2Findex.html%3F%26editable%3Dtrue%26editors%3D001%26key%3DiFrameKey-3e2e86de-7391-7ae7-12d3-0c31be8435c6%22%2C%22htmlAttrs%22%3A%7B%7D%2C%22head%22%3A%5B%22HEAD%22%2C%22el1000%22%2C%7B%7D%2C%5B%5B%22META%22%2C%22el1001%22%2C%7B%22charset%22%3A%22UTF-8%22%7D%2C%5B%5D%2C%22el1000%22%5D%2C%5B%22META%22%2C%22el1002%22%2C%7B%22name%22%3A%22robots%22%2C%22content%22%3A%22noindex%22%7D%2C%5B%5D%2C%22el1000%22%5D%2C%5B%22LINK%22%2C%22el1003%22%2C%7B%22rel%22%3A%22shortcut%20icon%22%2C%22type%22%3A%22image%2Fx-icon%22%2C%22href%22%3A%22https%3A%2F%2Fstatic.codepen.io%2Fassets%2Ffavicon%2Ffavicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico%22%7D%2C%5B%5D%2C%22el1000%22%5D%2C%5B%22LINK%22%2C%22el1004%22%2C%7B%22rel%22%3A%22mask-icon%22%2C%22type%22%3A%22%22%2C%22href%22%3A%22https%3A%2F%2Fstatic.codepen.io%2Fassets%2Ffavicon%2Flogo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg%22%2C%22color%22%3A%22%23111%22%7D%2C%5B%5D%2C%22el1000%22%5D%2C%5B%22LINK%22%2C%22el1005%22%2C%7B%22rel%22%3A%22canonical%22%2C%22href%22%3A%22https%3A%2F%2Fcodepen.io%2Fpen%3F%26editable%3Dtrue%26editors%3D001%22%7D%2C%5B%5D%2C%22el1000%22%5D%2C%22%5Cn%22%2C%5B%22STYLE%22%2C%22el1006%22%2C%7B%22class%22%3A%22cp-pen-styles%22%7D%2C%5B%5D%2C%22el1000%22%5D%2C%5B%22LINK%22%2C%22el1007%22%2C%7B%22href%22%3A%22https%3A%2F%2Fwchat.freshchat.com%2Fcss%2Fwidget.css%3Ft%3D1560838725391%22%2C%22rel%22%3A%22stylesheet%22%7D%2C%5B%5D%2C%22el1000%22%5D%2C%5B%22LINK%22%2C%22el1008%22%2C%7B%22href%22%3A%22https%3A%2F%2Fwchat.freshchat.com%2Fcss%2Fcb.css%3Ft%3D1560838726509%22%2C%22rel%22%3A%22stylesheet%22%7D%2C%5B%5D%2C%22el1000%22%5D%5D%2Cnull%5D%2C%22body%2

**Comment by davisp** [comment]
Jiffy will return values as `iodata()`. You appear to be attempting to get the size of the data encoded. You can use `erlang:iolist_size/1` or convert the output to a binary with `erlang:iolist_to_binary/1`.
