### ISSUE TITLE
if encode content is over nearly 1800 Byte ，it will return array.

### ISSUE THREAD

**Issue by lqy2183765** [davisp/jiffy#183]
If encode content is over nearly 1800 Byte ，it will return array.
But less then 1800 Byte, it will return string.
For example, json_test -> encode -> [a, b, c].
Old version don't hava this issues.Is it a bug?

**Comment by davisp** [comment]
You closed this so I think you figured it out. The return value is an `io_list()` which can be sent to a socket directly. Figured I'd leave a note in case others found this.

**Comment by edisonywh** [comment]
Hey @davisp! Thanks for commenting the reason, this did help me figure out my issue. I saw on the README that it encode could return an io_list but I'm not sure if that was the reason behind my issue.

I'm curious though, what is the reason for truncating it beyond X byte?

**Comment by davisp** [comment]
@edisonywh Its a performance optimization. Returning a single binary means you have to allocate extra space and do the copy. A lot of the use cases for jiffy are to generate json and pass it to a socket which accepts iolists so it's a bit of a waste in that common situation.

**Comment by edisonywh** [comment]
Cool thanks for the explanation! Are there any reason why it's ~1800 bytes then? I did a little digging, and found something related to `bytes_per_red`, is that related?

https://github.com/davisp/jiffy/blob/496d7f0ccd6aab1b2f7e133184e240d07047caaa/c_src/jiffy.h#L10

Also not sure if you could answer this, what I found was that my huge blob of JSON was split into one huge chunk, and then one tiny bit, I was wondering in cases of IO lists, does the size of the elements matter? Take for instance, I have a fixed size list of 1000 bytes, does it matter if it's split up to 2 chunks of 500 bytes vs 10 chunks of 100 bytes?

Thanks for your time Paul :)

**Comment by davisp** [comment]
The 1800 is a bit weird, but it'll somewhat depend on your specific JSON that's being encoded. The internal buffers use 2048 chunks. I'd have to grab a specific JSON bit to give a more detailed explanation on the exact threshold. 

https://github.com/davisp/jiffy/blob/496d7f0ccd6aab1b2f7e133184e240d07047caaa/c_src/encoder.c#L11

It shouldn't ever have differently sized chunks. For the  most part it should be one or more largish chunks followed by one that can be anywhere in the range for the tail of the encoding. The size of the elements going to a socket doesn't matter. You can see similar games if you look at the output of `io_lib:format/2` and the different ways it uses iolists in its return.

**Comment by edisonywh** [comment]
Ah okay I see, yeah I don't think for my case it happened at 1800, I was just using that as an example since that's what OP used.

Cool, thanks for the explanation, Paul!
