### ISSUE TITLE
Memory leak when encoding binary?

### ISSUE THREAD

**Issue by edisonywh** [davisp/jiffy#188]
So, obviously the usual use case is not to encode a binary, but we did have an edge case where we accidentally encode twice, and we are seeing some weird memory leaks that never gets garbage collected, hence this investigation.

[Reproduction Repo](https://github.com/edisonywh/jiffy_memory)

I pushed up an example repo here where I compared `:jiffy` with `Jason`, and `Jason` does not seem to suffer from this problem. Four scenarios were tested:

- Jiffy with Map
- Jiffy with Binary
- Jason with Map
- Jason with Binary

Here's how I ran the test:

> `Enum.map(0..10000, fn _ -> spawn(JiffyMemory, :run, [:jiffy, :bin]) end)`
(I ran them in a separate Process just to eliminate the possibility of IEx hogging up the refc)

And I basically eyeballed the result with `:observer.start`. Here are some snapshots from observer.

1) Before any operation:
Keep in mind I restart IEx after every operation anyway. This is just for control.

![image](https://user-images.githubusercontent.com/20277437/75434173-72b66300-5951-11ea-869f-5a9714026cae.png)

2) Jason with Map
The big spike on the left is when I ran the command. I'm mainly looking at `bin_alloc` here, you can see that it does not really spike up.

![image](https://user-images.githubusercontent.com/20277437/75434354-b315e100-5951-11ea-8bdb-4aa4600f2f6f.png)

3) Jiffy with Map
Looks relatively fine as well post-operation.

![image](https://user-images.githubusercontent.com/20277437/75434926-93cb8380-5952-11ea-9a81-8ba271cdcd49.png)

4) Jason with Binary
Huge spike at the beginning, but you can see it does come down to a rather normal usage after.

![Screenshot 2020-02-27 at 11 21 52](https://user-images.githubusercontent.com/20277437/75435494-6501dd00-5953-11ea-90c1-0d67e6cb22b7.png)

5) Jiffy with Binary
You can see the extremely huge spike at the beginning for bin_alloc and then it just never comes back down.

This exaggerated spike is because of the extremely large binary, but in one of our case it was dealing with small binary, and so it just keeps climbing up kb by kb, and eventually reaches a dangerous threshold.

![image](https://user-images.githubusercontent.com/20277437/75436081-4223f880-5954-11ea-8683-13edf2265ce6.png)

Running `:recon.bin_leak/1` doesn't help much because the binary is not able to be gc-ed anyway. Also tried to run manual `:erlang.garbage_collect` and that does not work either.

That being said my testing method might just be wrong so feel free to correct me as well, and let me know if you need anything else from my end.

**Comment by davisp** [comment]
Thanks for the report! This is fixed as of 0ba322e42171bb48ffdd0c053cef28a42eb35fc9 which is tagged and on hex.pm as version 1.0.4.

Turns out the issue was encoding a bare binary larger than 2041 bytes triggered a buffer reallocation that didn't deallocate the existing buffer.

**Comment by edisonywh** [comment]
Thanks for the quick turnaround, @davisp! I can confirm that the issue is now fixed, cheers!
