### ISSUE TITLE
Cannot compile jiffy in win10

### ISSUE THREAD

**Issue by xujiaja** [davisp/jiffy#194]
![image](https://user-images.githubusercontent.com/23472286/77418462-e25d2800-6e01-11ea-9465-490a671dde46.png)

**Comment by davisp** [comment]
@wohali Does this ring any bells for you?

**Comment by wohali** [comment]
That looks like an encoding error in the console. Very confusing. Never seen that before.

@xujiaja Is that Chinese 亂碼?

**Comment by wohali** [comment]
@davisp Guessing, but maybe they don't have Visual Studio installed and that error is saying `cl.exe` couldn't be found?

**Comment by xujiaja** [comment]
> @davisp Guessing, but maybe they don't have Visual Studio installed and that error is saying `cl.exe` couldn't be found?

After install visual studio2015,error
 
![image](https://user-images.githubusercontent.com/23472286/77508651-286bc780-6ea6-11ea-870e-83ab873ca1db.png)

**Comment by xujiaja** [comment]
> > @davisp Guessing, but maybe they don't have Visual Studio installed and that error is saying `cl.exe` couldn't be found?
> 
> After install visual studio2015,error
> 
> ![image](https://user-images.githubusercontent.com/23472286/77508651-286bc780-6ea6-11ea-870e-83ab873ca1db.png)
> ==> jiffy (compile)
> link: extra operand ‘c_src/jiffy.o’
> Try 'link --help' for more information.
> sh(cmd /q /c link.exe c_src/decoder.o c_src/encoder.o c_src/jiffy.o c_src/termstack.o c_src/utf8.o c_src/util.o c_src/doubles.o c_src/objects.o c_src/double-conversion/bignum-dtoa.o c_src/double-conversion/bignum.o c_src/double-conversion/cached-powers.o c_src/double-conversion/diy-fp.o c_src/double-conversion/double-conversion.o c_src/double-conversion/fast-dtoa.o c_src/double-conversion/fixed-dtoa.o c_src/double-conversion/strtod.o /DLL /LIBPATH:c:/Users/xujiajia/sdk/erl10.7/lib/erl_interface-3.13.2/lib erl_interface.lib ei.lib /OUT:priv/jiffy.dll)
> failed with return code 1 and the following output:
> link: extra operand ‘c_src/jiffy.o’
> Try 'link --help' for more information.
> 
> ERROR: Command [compile] failed!
> make: *** [Makefile:19: build] Error 1

Resolved，Because I use git bash link，thx

**Comment by davisp** [comment]
@wohali Thanks! Looks like you nailed it in one.
