### ISSUE TITLE
return_trailer and bignum handling broken

### ISSUE THREAD

**Issue by aboroska** [davisp/jiffy#206]
Version: `1.0.6` on Erlang/OTP 22

The following works as expected:

    > jiffy:decode(<<"{\"amount\":-50000000000000000000}">>, [return_maps]).
    #{<<"amount">> => -50000000000000000000}

With `return_trailer` option though the value gets wrapped in` {bignum, Val}`

    > jiffy:decode(<<"{\"amount\":-50000000000000000000}{}">>, [return_maps, return_trailer]).
    {has_trailer,#{<<"amount">> =>
                   {bignum,<<"-50000000000000000000">>}},
             <<"{}">>}

Is this some oversight in the trailer processing part?

**Comment by davisp** [comment]
Looks like a bug yeah. I'll try and find time tomorrow to look at it.

**Comment by davisp** [comment]
Bug is fixed in <del>1.0.7</del> 1.0.8. Pushed on version and then thought slightly harder. Thanks for the report!
