### ISSUE TITLE
solution to the error jiffy/c_src/decoder.c(4): fatal error C1083: Cannot open include file: 'assert.h': No such file or directory

### ISSUE THREAD

**Issue by Spycsh** [davisp/jiffy#215]
Hi, for anyone who is confused by the assert.h problem when you try to compile jiffy on windows using Visual Studio 2019 or other versions like me, you may initialize the compilation environement for 'x64' to solve the problem, which means that you can do either of the following two things:
1. search for `x64 Native Tools Command Prompt` on your windows and `cd` to the folder of jiffy and do `make` there
2. or in an ordinary command prompt enter `vcvarsall.bat x64` to initialize the environment and compile

This might be the solution to #144 and #59

**Comment by v1d3rm3** [comment]
@Spycsh, how did you do it? `make` command doesn't come with Visual C++ Build Tools. There is only `nmake`, but it doesn't work with the Makefile present in repository.

**Comment by Spycsh** [comment]
@v1d3rm3 , maybe you can refer to cygwin and choco installation of `make` command on windows

**Comment by nickva** [comment]
Since Windows 7 is not support any longer, this might not apply?

Recently we added a GH Action CI which does test jiffy on whatever Github uses for their 2019 and 2022 Windows runners. There is seems to pass currently. I'll close the issue, but feel free to re-open if it's broken on recent Windows.

Here is what I used to get the location of the compiler for Windows 2019, for instance:

```powershell
        $path = vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -nologo -nocolor -property installationPath
        if ($path) {
            $path = join-path $path '\VC\Auxiliary\Build\vcvars64.bat'
            if (test-path $path) {
                cmd /s /c """$path"" $args && set" | where { $_ -match '(\w+)=(.*)' } | foreach {
                    $null = new-item -force -path "Env:\$($Matches[1])" -value $Matches[2]
                }
            }
        }
```
