### ISSUE TITLE
there is a error when windows os use 

### ISSUE THREAD

**Issue by CFCEN** [davisp/jiffy#223]
===> Verifying dependencies...
===> Compiling jiffy
'.' ²»ÊÇÄÚ²¿»òÍâ²¿ÃüÁî£¬Ò²²»ÊÇ¿ÉÔËÐÐµÄ³ÌÐò
»òÅú´¦ÀíÎÄ¼þ¡£
===> Hook for compile failed!

The above is a garbled message.
After parsing

===> Verifying dependencies...
===> Compiling jiffy
'.' is not recognized as an internal or external command,
operable program or batch file.
===> Hook for compile failed!

**Comment by nickva** [comment]
The new release 1.1.2 is now compiling in CI at least on Windows 2019 and 2022. Wonder if it would fix this issue? Trying using a later Erlang (26 or so) and set up your terminal to display unicode character perhaps: `erl +pc unicode`.

https://www.erlang.org/doc/apps/stdlib/unicode_usage

**Comment by CFCEN** [comment]
I sincerely thank you for your help.
