### ISSUE TITLE
jiffy 1.1.2 tagged and released, but not published in hex.pm

### ISSUE THREAD

**Issue by badlop** [davisp/jiffy#240]
Hello!

Recently, a new version of jiffy was tagged and released: 1.1.2. However, it isn't yet published in hex.pm

**Comment by nickva** [comment]
Thanks @badlop. We'll try to make one in the next few days.

**Comment by nickva** [comment]
Release published to hex https://hex.pm/packages/jiffy/1.1.2

Thanks for the reminder, @badlop!
