### ISSUE TITLE
Compile error on windows with MinGW

### ISSUE THREAD

**Issue by Enouk** [davisp/jiffy#40]
Hi I get the following error when trying to compile on windows with a MinGW setup 32 bits

==> jiffy (compile)
Compiling c_src/decoder.c
cc: error: /Wall: No such file or directory
cc: error: /DWIN32: No such file or directory
cc: error: /D_WINDOWS: No such file or directory
cc: error: /D_WIN32: No such file or directory
cc: error: /DWINDOWS: No such file or directory
ERROR: cmd /q /c cc -c /Wall /DWIN32 /D_WINDOWS /D_WIN32 /DWINDOWS -g -Wall -fPIC  -Ic:/PROGRA~2/ERL510~1.1/lib/erl_interface-3.7.11/include -Ic:/PROGRA~2/ERL510~1.1/erts-5.10.1/include   c_src/decoder.c -o c_src/decoder.o failed with error: 1 and output:
cc: error: /Wall: No such file or directory
cc: error: /DWIN32: No such file or directory
cc: error: /D_WINDOWS: No such file or directory
cc: error: /D_WIN32: No such file or directory
cc: error: /DWINDOWS: No such file or directory

**Comment by davisp** [comment]
Closing this. If someone wants to figure out a patch for MinGW builds that doesn't break the other windows builds I'd merge it.
