### ISSUE TITLE
error when compiling on Windows 7

### ISSUE THREAD

**Issue by tomhoward87** [davisp/jiffy#59]
I'm getting an error when I try to compile on Windows 7 - I have rebar installed and on my path, along with cl from Visual Studio 2010 (which I understand should be recent enough). However it seems that the file "assert.h" is missing:

$ rebar compile
==> jiffy (compile)
Compiling c_src/decoder.c
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.30319.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

decoder.c
c_src/decoder.c(4) : fatal error C1083: Cannot open include file: 'assert.h': No such file or directory
ERROR: compile failed while processing c:/Users/gbhowarto/code/orca/deps/jiffy: rebar_abort

**Comment by davisp** [comment]
Recent reports suggests windows builds are working so I'm gonna close this.

Though I will note that I think they're only working with Visual Studio or whatever that thing is called.
