### ISSUE TITLE
Nif problem

### ISSUE THREAD

**Issue by cclam0827** [davisp/jiffy#62]
I got function not found when I call jiffy:encode/1 and jiffy:decode/1, anyone one know whats problem?

1> jiffy:encode(<<>>).
*\* exception error: undefined function jiffy:encode/1
2> 
=ERROR REPORT==== 13-Aug-2014::13:47:04 ===
The on_load function for module jiffy returned {error,
                                                {bad_lib,
                                                 "Function not found jiffy:nif_decode/1"}}

**Comment by tommyjcarpenter** [comment]
@davisp  I can't seem to use Jiffy with just `rebar3 compile`. I hit this issue that is discussed in this thread. The fix I got working is:

```
rebar3 compile
cd _build/default/lib/jiffy/
make
```

Why can't I just do rebar3 compile? My rebar config contains

```
{deps, [
    {jiffy, ".*", {git, "git://github.com/davisp/jiffy.git", {branch, "master"}}},
```

and my application src contains

```
{applications,
 [kernel,
  stdlib,
  lager,
  inets,
  jiffy,
```

**Comment by tommyjcarpenter** [comment]
vote to reopen

**Comment by tommyjcarpenter** [comment]
@davisp nevermind, sorry for the panic. It appears rebar3 had a cached version from a couple of months ago and this was upgraded very recently to fix this issue. Running `rebar3 upgrade` fixed the issue. Thanks!
