### ISSUE TITLE
Add the possiblity to test an Erlang term wether it is valid

### ISSUE THREAD

**Issue by hanikesn** [davisp/jiffy#63]
I'd like to safe Erlang terms persistently. They are to be encoded by jiffy some time afterwards. To prevent encoding errors, I'd like to check the Erlang terms, before I save them without actually encoding them.

The signature would basically look like this:
check(EJSON) -> ok|{err, Reason}

Would that feature be useful for anyone else?

**Comment by davisp** [comment]
Given that it'd basically require just throwing away the encoded result I'm reluctant to put it into Jiffy directly as that would probably be a good surprise for someone that didn't understand what it was doing to run the check. Given that its also a fairly trivial function to write I'll probably just leave this for client code to implement if/when they want it.

    check(Term) ->
        try
            jiffy:encode(Term),
            ok
       catch throw:Error ->
           Error
        end.
