### ISSUE TITLE
Error when building on Windows

### ISSUE THREAD

**Issue by GxFlint** [davisp/jiffy#83]
I was having the same problem from issue "error when compiling on Windows 7 #59"
I got around that by running the build commands from the Visual Studio Command Prompt.

After compiling the .c code, rebar tries to connect to the git repository and I get this error:

==> Jiffy (compile)
ERROR: cmd /q /c git describe --always --tags failed with error: 128 and output:
fatal: Not a valid object name HEAD

ERROR: compile failed while processing C:/Erlang/Jiffy: rebar_abort

Running: git symbolic-ref HEAD
Returns:
refs/heads/master

**Comment by OvermindDL1** [comment]
Getting this when compiling it via `mix`:
```sh
===> Compiling jiffy
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by antipax** [comment]
@OvermindDL1 same here!

@davisp - think this might be related to the rebar pre-hook for "./enc compile". Let me know if I can help!

**Comment by walter-weinmann** [comment]
I have the same problem, but I have no idea how the solution looks. Please help.

**Comment by davisp** [comment]
I haven't got the slightest on this. Sounds to me like its failing when rebar tries to get a version from Git which makes this a rebar issue. I don't do any dev work on Windows so I'm afraid I can't be much help here.

**Comment by OvermindDL1** [comment]
> think this might be related to the rebar pre-hook for "./enc compile". Let me know if I can help!

This would indeed not work on windows, it is a bad hook.

**Comment by davisp** [comment]
@OvermindDL1 Any idea what's proper for running that? The original report listed git describe as the failing command. Though I do see the follow ups are different now.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Any idea what's proper for running that? The original report listed git describe as the failing command. Though I do see the follow ups are different now.

Well it most certainly would *not* be called `enc`.  ^.^

It looks like a an escript, so the proper command would be to call it via `escript`, not calling it directly, so probably `escript ./enc compile` or maybe just `escript enc compile`?

**Comment by davisp** [comment]
Its an escript yeah. Lemme try that locally and will push a change if it works.

**Comment by davisp** [comment]
Someone want to try giving master a try?

**Comment by antipax** [comment]
I'll try in about an hour and report back.
