### ISSUE TITLE
array of map not works

### ISSUE THREAD

**Issue by ChinaXing** [davisp/jiffy#88]
(cat@lambda.net)22> jiffy:encode({[{chart_data,[{a,b}]}]}).
** exception throw: {error,{invalid_ejson,{a,b}}}
     in function  jiffy:encode/2 (src/jiffy.erl, line 41)

**Comment by davisp** [comment]
You want:

    jiffy:encode({[{chart_data,{[{a,b}]}}]}).

You were missing the 1-tuple wrapping of the inner object so it looked like an array of something it couldn't encode.
