### ISSUE TITLE
integrate with ejabberd 2.1.11

### ISSUE THREAD

**Issue by gsnarawat** [davisp/jiffy#90]
I have already installed and working copy of ejabbed 2.1.11, with an application.
Is there a way I can integrate jiffy with it to support json parsing?

**Comment by aleczadikian** [comment]
Add it as a rebar dependency in Ejabberd's rebar file, then make clean, then make. I've been using Jiffy with Ejabberd, and it works great!

**Comment by davisp** [comment]
I'm not familiar with ejabberd but it sounds like @aleczadikian's answer should be sufficient.
