### ISSUE TITLE
UTF-8 not actually supported (even in binaries)?

### ISSUE THREAD

**Issue by lostcolony** [davisp/jiffy#95]
I've been using Jiffy for a while, but I recently ran into an issue where a ñ was being passed in, and Jiffy choked. ñ is a single byte UTF-8 character, 241, and I expected it to pass. Per the following - 

> list_to_binary([109,97,241,97,110,97]).
<<"mañana">>

> jiffy:decode(<<"{\"a\" : \"manana\"}">>).
{[{<<"a">>,<<"manana">>}]}

> jiffy:decode(<<"{\"a\" : \"mañana\"}">>).
** exception throw: {error,{11,invalid_string}}

Am I missing something?

**Comment by davisp** [comment]
241 is the character code for ñ, not the UTF-8 encoding of that code point.

<code>
Eshell V6.0  (abort with ^G)
1> L = [109,97,241,97,110,97].
"mañana"
2> UTF8 = xmerl_ucs:to_utf8(L).
"maÃ±ana"
3> jiffy:encode(list_to_binary(UTF8)).
<<"\"mañana\""/utf8>>
4> io:format("~w~n", [UTF8]).
[109,97,195,177,97,110,97]
</code>

Notice that the UTF-8 encoding is actually the two bytes [1895, 177].

**Comment by davisp** [comment]
Wow. Screwed that last comment up. Edited in place.

**Comment by lostcolony** [comment]
Aaah, okay. Great, thanks!
