### ISSUE TITLE
When included in a rebar3 project, jiffy will not compile on its own

### ISSUE THREAD

**Issue by henrythor** [davisp/jiffy#96]
When used in a project that uses rebar3, the developer will need to go into _build/default/lib/jiffy and type make, since there are no hooks to run make.

**Comment by qrilka** [comment]
See line about `port compiler` at http://www.rebar3.org/docs/from-rebar-2x-to-rebar3

**Comment by Neurotec** [comment]
see  [https://github.com/blt/port_compiler#use-with-existing-dependency](https://github.com/blt/port_compiler#use-with-existing-dependency)

add to rebar.config
~~~erlang
{deps, [jiffy]}.

{overrides,
 [{override, jiffy, [
     {plugins, [pc]},
     {artifacts, ["priv/jiffy.so"]},
     {provider_hooks, [
         {post,
             [
             {compile, {pc, compile}},
             {clean, {pc, clean}}
             ]
          }]
      }
  ]}
]}.
~~

**Comment by davisp** [comment]
I've finally gotten around to figuring out the dynamic config for rebar2/3 differentiation. Can anyone that cares try this branch:

https://github.com/davisp/jiffy/pull/118

**Comment by vendethiel** [comment]
I think this one can be closed?

**Comment by davisp** [comment]
Yep.
