### ISSUE TITLE
-Werror causes build to abort

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [davisp/jiffy#97]
Hi,

When using the current Fedora 22 default compiler

```
g++ (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
the build aborts:
```
Compiling /home/user/project/deps/jiffy/c_src/double-conversion/bignum.cc
/home/user/project/deps/jiffy/c_src/double-conversion/bignum.cc: In member function ‘void double_conversion::Bignum::AssignDecimalString(double_conversion::Vector<const char>)’:
/home/user/project/deps/jiffy/c_src/double-conversion/bignum.cc:101:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void Bignum::AssignDecimalString(Vector<const char> value) {
      ^
cc1plus: all warnings being treated as errors
```

Removing -Werror lets the build complete sucessfully, with no additional warnings.

**Comment by davisp** [comment]
What version of jiffy are you on? In #89 it was claimed that this was fixed.

**Comment by davisp** [comment]
And the 0.14.1 tag should include that commit if you're still on 0.13.3

**Comment by Leonidas-from-XIV** [comment]
I was on 0.13.3, but updating to 0.14.1 did not help since the change in 446e284 was reverted back in 5d6b265.

Reapplying the change in 446e284 does solve the build-warning problem.

**Comment by davisp** [comment]
Doh! My bad. I've submitted the change upstream so hopefully this won't happen again. I'll reapply that patch and tag 0.14.2.

**Comment by davisp** [comment]
Should be fixed now.
